routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/',[\App\View\Components\AppLayout::class,'render']);
Route::group(['as'=>'admin.','middleware'=>'auth'], function(){

    Route::get('/', [\App\Http\Controllers\Layouts\RegisController::class,'pendaftaran'])->name('index');
    Route::get('/test', function(){
        return view('test');
    })->name('index');

    Route::resource('ukm',\App\Http\Controllers\Layouts\UkmController::class);

    Route::resource('mahasiswa',\App\Http\Controllers\Layouts\MahasiswaController::class);
    Route::get('mahasiswa/{id}/destroy', [\App\Http\Controllers\Layouts\MahasiswaController::class,'destroy'])->name('mahasiswaDestroy');

    Route::resource('leader',\App\Http\Controllers\Layouts\LeaderController::class);
    Route::get('leader/{id}/destroy', [\App\Http\Controllers\Layouts\LeaderController::class,'destroy'])->name('leaderDestroy');

    Route::get('ukm/{id}/destroy', [\App\Http\Controllers\Layouts\UkmController::class,'destroy'])->name('ukmDestroy');

    Route::get('ukm/galleries/{id}', [\App\Http\Controllers\Layouts\GalleryController::class,'index'])->name('galleries.index');
    Route::post('ukm/galleries/{id}/create', [\App\Http\Controllers\Layouts\GalleryController::class,'create'])->name('galleries.create');
    Route::post('ukm/galleries/thumbnail', [\App\Http\Controllers\Layouts\GalleryController::class,'image'])->name('galleries.thumbnail');
    Route::delete('ukm/galleries/selectDelete', [\App\Http\Controllers\Layouts\GalleryController::class,'selectDelete'])->name('galleries.selectDelete');
    Route::get('ukm/Achievements/{ukm_id}/{gallery_id}', [\App\Http\Controllers\Layouts\GalleryController::class,'destroyAchievements'])->name('destroy.achievements');

    Route::post('ukm/galleries/{id}/create/achievements', [\App\Http\Controllers\Layouts\GalleryController::class,'achievements'])->name('galleries.achievements');

    Route::get('ukm/staff/{id}', [\App\Http\Controllers\Layouts\StaffController::class,'create'])->name('staff.create');
    Route::post('ukm/staff/{id}', [\App\Http\Controllers\Layouts\StaffController::class,'store'])->name('staff.store');
    Route::get('ukm/staff/{idUKM}/delete', [\App\Http\Controllers\Layouts\StaffController::class,'destroy'])->name('staff.destroy');

    Route::resource('tags', \App\Http\Controllers\Layouts\TagController::class);
    Route::get('tags/{id}/destroy', [\App\Http\Controllers\Layouts\TagController::class,'destroy'])->name('tagsDestroy');

    Route::resource('categories', \App\Http\Controllers\Layouts\CategoryController::class);
    Route::get('categories/{id}/destroy', [\App\Http\Controllers\Layouts\CategoryController::class,'destroy'])->name('categoriesDestroy');

    Route::resource('carousels', \App\Http\Controllers\Layouts\CarouselsController::class);
    Route::get('carousels/{id}/destroy', [\App\Http\Controllers\Layouts\CarouselsController::class,'destroy'])->name('carouselsDestroy');

    Route::get('statistika-pendaftaran/', [\App\Http\Controllers\Layouts\RegisController::class,'pendaftaran'])->name('pendaftaran.index');

    Route::get('statistika-pendaftaran/{id}', [\App\Http\Controllers\Layouts\RegisController::class,'filter'])->name('filter.index');
    Route::get('statistika-pendaftaran/view-web/{year}', [\App\Http\Controllers\Layouts\RegisController::class,'filterWeb'])->name('filterWeb.index');
    Route::post('statistika-pendaftaran/view-ukm/', [\App\Http\Controllers\Layouts\RegisController::class,'actionFilterWeb'])->name('actionFilterUkm');
    Route::get('statistika-pendaftaran/view-ukm/{ukm}/{year}', [\App\Http\Controllers\Layouts\RegisController::class,'Filterukm'])->name('filterUkm');

    Route::get('statistika-pendaftaran/detail/{id}/show',[\App\Http\Controllers\Layouts\RegisController::class,'show'])->name('pendaftaran.show');

    Route::resource('faqs', \App\Http\Controllers\Layouts\FaqController::class);
    Route::get('faqs/{id}/destroy', [\App\Http\Controllers\Layouts\FaqController::class,'destroy'])->name('faqsDestroy');

    Route::resource('questions', \App\Http\Controllers\Layouts\QuestionController::class);
    Route::get('questions/{id}/destroy', [\App\Http\Controllers\Layouts\QuestionController::class,'destroy'])->name('questionsDestroy');

    Route::resource('suggestions', \App\Http\Controllers\Layouts\SuggestionController::class);
    Route::get('suggestions/{id}/destroy', [\App\Http\Controllers\Layouts\SuggestionController::class,'destroy'])->name('suggestionsDestroy');

});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'guest'], function(){
    Route::get('/login', [\App\Http\Controllers\Auth\AuthController::class,'showFormLogin'])->name('formLogin');
    Route::post('/login/action',[\App\Http\Controllers\Auth\AuthController::class,'login'])->name('login');
    Route::get('/regis', [\App\Http\Controllers\Auth\AuthController::class,'showFormRegister'])->name('formRegister');
    Route::post('/regis/action',[\App\Http\Controllers\Auth\AuthController::class,'register'])->name('register');
    Route::post('/logout',[\App\Http\Controllers\Auth\AuthController::class,'logout'])->name('logout')->withoutMiddleware('guest');
});

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    use HasFactory;

    public function ukms(){
        return $this->belongsTo(Ukm::class,'ukm_id');
    }
}

app/Http/Controllers/ApiV1/FaqController.php
<?php

namespace App\Http\Controllers\ApiV1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FaqController extends Controller
{
    public function create ($id){

    }
}

app/Http/Controllers/Layouts/CarouselsController.php
<?php

namespace App\Http\Controllers\Layouts;

use App\Http\Controllers\Controller;
use App\Models\Carousel;
use App\Models\Category;
use App\Models\Question;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class CarouselsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            $data = Carousel::all();

//        dd($data);
            return DataTables::of($data)->addColumn('img', function($data){
//                $img = '<img src="'.asset($data->img).'">';
                $img = '<img src="'.asset($data->img).'" class="img-fluid img-thumbnail">';
                return $img;
            })
                ->addColumn('action', function($data){
                    $button = '<a href="carousels/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.carouselsDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['img','action'])
                ->make(true);
        }

        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.carousels.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.carousels.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Carousel();
        $validates = [
            'image'      => 'required',
            'dsc'      => 'required',
        ];
        $request->validate($validates);

        $file = $request->file('image');

        $name = rand(999999,1);
        $extension = $file->getClientOriginalExtension();
        $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
        Storage::putFileAs('public',$file,$newName);

        $imgDB = 'storage/'.$newName;
        $data->img = $imgDB;
        $data->dsc = $request->dsc;

        $data->save();

        return redirect()->route('admin.carousels.index')->withSuccess('berhasil ditambah');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Carousel::find($id);
        view()->share([
            'data' => $data,
            'notif' => $this->notif()

        ]);

        return view('layouts.carousels.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Carousel::find($id);

        if ($file = $request->file('image') == null){
            $data->img = $request->newImage;
        }else{
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->img = $imgDB;
//            dd($imgDB);
        }


        $data->dsc = $request->dsc;
        $data->save();
        return redirect()->route('admin.carousels.index')->withSuccess('berhasil di update');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Carousel::findOrFail($id);
        $data->delete();

        return redirect()->back()->with('danger','data has been deleted');
    }
}

app/Http/Controllers/Layouts/CategoryController.php
<?php

namespace App\Http\Controllers\Layouts;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            $data = Category::all();

//        dd($data);
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<a href="categories/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.categoriesDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.category.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Category();

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);

        $file = $request->file('image');

        $name = rand(999999,1);
        $extension = $file->getClientOriginalExtension();
        $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
        Storage::putFileAs('public',$file,$newName);

        $imgDB = 'storage/'.$newName;
        $data->logo = $imgDB;

        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->dsc;

        $data->save();

        return redirect()->route('admin.categories.index')->with('success','success add UKM');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Category::findOrFail($id);
        view()->share([
            'data' => $data,
                'notif' => $this->notif()
        ]);
        return view('layouts.category.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = Category::findOrFail($id);

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);


        if ($request->file('image')){
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->logo = $imgDB;
        }else{
            $data->logo = $request->newImage;
        }


        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->dsc;

        $data->save();

        return redirect()->route('admin.categories.index')->with('success','edit add UKM');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Category::findOrFail($id);
        $data->delete();

        return redirect()->back()->with('danger','data has been deleted');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use App\Models\User;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public $title;

    public function __construct($title = 'SI-UKM')
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {

        return view('layouts.app');
    }
}

resources/views/layouts/faq/create.blade.php
<x-app-layout >
    <style>
        .btn-primary, .btn-primary.disabled {
            box-shadow: 0 0 0 #FFC13B;
            background-color: #FFC13B;
            border-color: #FFC13B;
        }
        .btn-primary:active, .btn-primary:hover, .btn-primary.disabled:active, .btn-primary.disabled:hover {
            background-color: #1E3D59 !important;
        }
    </style>

    @push('style')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    @endpush
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Daftar FAQ</h1>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{route('admin.faqs.store')}}" method="post">
                                    @csrf
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">UKM</label>
                                        <div class="col-sm-12 col-md-7">
                                            <select class="selectpicker" data-width="fit" data-size="5"  name="ukm" data-live-search="true">
                                                @foreach($ukms as $ukm)
                                                    <option value="{{$ukm->id}}" data-tokens="{{$ukm->name}}">{{$ukm->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pertanyaan</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="value" id="value" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jawaban</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="answer" id="answer" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Tambah</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</x-app-layout>

resources/views/layouts/faq/edit.blade.php
<x-app-layout >
    <style>
        .btn-primary, .btn-primary.disabled {
            box-shadow: 0 0 0 #FFC13B;
            background-color: #FFC13B;
            border-color: #FFC13B;
        }
        .btn-primary:active, .btn-primary:hover, .btn-primary.disabled:active, .btn-primary.disabled:hover {
            background-color: #1E3D59 !important;
        }
    </style>

    @push('style')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    @endpush
<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Daftar FAQ</h1>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Edit FAQ UKM</h4>

                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <form action="{{route('admin.faqs.update',$data->id)}}" method="post">
                                    @csrf
                                    @method('put')
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">UKM</label>
                                        <div class="col-sm-12 col-md-7">
                                            <select class="selectpicker" data-width="fit" data-size="5"  name="ukm" data-live-search="true">
                                                <option value=" {{$data->ukms->id}}" data-tokens="{{$data->ukms->name}}" >{{$data->ukms->name}}</option>
                                                @foreach($ukms as $ukm)
                                                    <option value="{{$ukm->id}}" data-tokens="{{$ukm->name}}" >{{$ukm->name}}</option>
                                                @endforeach
                                            </select>

                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pertanyaan</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="value" value=" {{$data->value}}" id="value" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jawaban</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="answer" value=" {{$data->answer}}" id="answer" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Edit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</x-app-layout>

resources/views/layouts/faq/index.blade.php
<x-app-layout >
    <style>
        .btn-primary, .btn-primary.disabled {
            box-shadow: 0 0 0 #FFC13B;
            background-color: #FFC13B;
            border-color: #FFC13B;
        }
        .btn-primary:active, .btn-primary:hover, .btn-primary.disabled:active, .btn-primary.disabled:hover {
            background-color: #1E3D59 !important;
        }
        .table-top{
            background-color: #1E3D59 !important;
            color: #FFFFFF;
        }
    </style>

    @push('style')
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/datatables.min.css">
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css">
    @endpush
        <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Daftar FAQ</h1>
            </div>
            <x-partials.notice/>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4><a href="{{route('admin.faqs.create')}}" class="btn btn-primary">TAMBAH DATA</a> </h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-width" id="item">
                                        <thead>
                                            <tr class="table-top">
                                                <th style="color: #ffffff">UKM</th>
                                                <th style="color: #ffffff">Pertanyaan</th>
                                                <th style="color: #ffffff">Jawaban</th>
                                                <th style="color: #ffffff">Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
        @push('script')
            <script type="text/javascript">
                $(document).ready(function(){
                    $('#item').DataTable({
                        @include('components.search')
                        processing: true,
                        serverSide: true,
                        ajax: {
                            url: "{{route('admin.faqs.index')}}",
                        },
                        columns: [
                            {
                                data: 'ukm',
                                name: 'ukm'
                            },
                            {
                                data: 'value',
                                name: 'value'
                            },
                            {
                                data: 'answer',
                                name: 'answer'
                            },
                            {
                                data: 'action',
                                name: 'action',
                                orderable: false
                            },

                        ]
                    });
                });
            </script>

        @endpush
</x-app-layout>