routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/',[\App\View\Components\AppLayout::class,'render']);
Route::group(['as'=>'admin.','middleware'=>'auth'], function(){

    Route::get('/', [\App\Http\Controllers\Layouts\RegisController::class,'pendaftaran'])->name('index');
    Route::get('/test', function(){
        return view('test');
    })->name('index');

    Route::resource('ukm',\App\Http\Controllers\Layouts\UkmController::class);

    Route::resource('mahasiswa',\App\Http\Controllers\Layouts\MahasiswaController::class);
    Route::get('mahasiswa/{id}/destroy', [\App\Http\Controllers\Layouts\MahasiswaController::class,'destroy'])->name('mahasiswaDestroy');

    Route::resource('leader',\App\Http\Controllers\Layouts\LeaderController::class);
    Route::get('leader/{id}/destroy', [\App\Http\Controllers\Layouts\LeaderController::class,'destroy'])->name('leaderDestroy');

    Route::get('ukm/{id}/destroy', [\App\Http\Controllers\Layouts\UkmController::class,'destroy'])->name('ukmDestroy');

    Route::get('ukm/galleries/{id}', [\App\Http\Controllers\Layouts\GalleryController::class,'index'])->name('galleries.index');
    Route::post('ukm/galleries/{id}/create', [\App\Http\Controllers\Layouts\GalleryController::class,'create'])->name('galleries.create');
    Route::post('ukm/galleries/thumbnail', [\App\Http\Controllers\Layouts\GalleryController::class,'image'])->name('galleries.thumbnail');
    Route::delete('ukm/galleries/selectDelete', [\App\Http\Controllers\Layouts\GalleryController::class,'selectDelete'])->name('galleries.selectDelete');
    Route::get('ukm/Achievements/{ukm_id}/{gallery_id}', [\App\Http\Controllers\Layouts\GalleryController::class,'destroyAchievements'])->name('destroy.achievements');

    Route::post('ukm/galleries/{id}/create/achievements', [\App\Http\Controllers\Layouts\GalleryController::class,'achievements'])->name('galleries.achievements');

    Route::get('ukm/staff/{id}', [\App\Http\Controllers\Layouts\StaffController::class,'create'])->name('staff.create');
    Route::post('ukm/staff/{id}', [\App\Http\Controllers\Layouts\StaffController::class,'store'])->name('staff.store');
    Route::get('ukm/staff/{idUKM}/delete', [\App\Http\Controllers\Layouts\StaffController::class,'destroy'])->name('staff.destroy');

    Route::resource('tags', \App\Http\Controllers\Layouts\TagController::class);
    Route::get('tags/{id}/destroy', [\App\Http\Controllers\Layouts\TagController::class,'destroy'])->name('tagsDestroy');

    Route::resource('categories', \App\Http\Controllers\Layouts\CategoryController::class);
    Route::get('categories/{id}/destroy', [\App\Http\Controllers\Layouts\CategoryController::class,'destroy'])->name('categoriesDestroy');

    Route::resource('carousels', \App\Http\Controllers\Layouts\CarouselsController::class);
    Route::get('carousels/{id}/destroy', [\App\Http\Controllers\Layouts\CarouselsController::class,'destroy'])->name('carouselsDestroy');

    Route::get('statistika-pendaftaran/', [\App\Http\Controllers\Layouts\RegisController::class,'pendaftaran'])->name('pendaftaran.index');

    Route::get('statistika-pendaftaran/{id}', [\App\Http\Controllers\Layouts\RegisController::class,'filter'])->name('filter.index');
    Route::get('statistika-pendaftaran/view-web/{year}', [\App\Http\Controllers\Layouts\RegisController::class,'filterWeb'])->name('filterWeb.index');
    Route::post('statistika-pendaftaran/view-ukm/', [\App\Http\Controllers\Layouts\RegisController::class,'actionFilterWeb'])->name('actionFilterUkm');
    Route::get('statistika-pendaftaran/view-ukm/{ukm}/{year}', [\App\Http\Controllers\Layouts\RegisController::class,'Filterukm'])->name('filterUkm');

    Route::get('statistika-pendaftaran/detail/{id}/show',[\App\Http\Controllers\Layouts\RegisController::class,'show'])->name('pendaftaran.show');

    Route::resource('faqs', \App\Http\Controllers\Layouts\FaqController::class);
    Route::get('faqs/{id}/destroy', [\App\Http\Controllers\Layouts\FaqController::class,'destroy'])->name('faqsDestroy');

    Route::resource('questions', \App\Http\Controllers\Layouts\QuestionController::class);
    Route::get('questions/{id}/destroy', [\App\Http\Controllers\Layouts\QuestionController::class,'destroy'])->name('questionsDestroy');

    Route::resource('suggestions', \App\Http\Controllers\Layouts\SuggestionController::class);
    Route::get('suggestions/{id}/destroy', [\App\Http\Controllers\Layouts\SuggestionController::class,'destroy'])->name('suggestionsDestroy');

});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'guest'], function(){
    Route::get('/login', [\App\Http\Controllers\Auth\AuthController::class,'showFormLogin'])->name('formLogin');
    Route::post('/login/action',[\App\Http\Controllers\Auth\AuthController::class,'login'])->name('login');
    Route::get('/regis', [\App\Http\Controllers\Auth\AuthController::class,'showFormRegister'])->name('formRegister');
    Route::post('/regis/action',[\App\Http\Controllers\Auth\AuthController::class,'register'])->name('register');
    Route::post('/logout',[\App\Http\Controllers\Auth\AuthController::class,'logout'])->name('logout')->withoutMiddleware('guest');
});

app/Http/Controllers/Layouts/CarouselsController.php
<?php

namespace App\Http\Controllers\Layouts;

use App\Http\Controllers\Controller;
use App\Models\Carousel;
use App\Models\Category;
use App\Models\Question;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class CarouselsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            $data = Carousel::all();

//        dd($data);
            return DataTables::of($data)->addColumn('img', function($data){
//                $img = '<img src="'.asset($data->img).'">';
                $img = '<img src="'.asset($data->img).'" class="img-fluid img-thumbnail">';
                return $img;
            })
                ->addColumn('action', function($data){
                    $button = '<a href="carousels/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.carouselsDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['img','action'])
                ->make(true);
        }

        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.carousels.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.carousels.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Carousel();
        $validates = [
            'image'      => 'required',
            'dsc'      => 'required',
        ];
        $request->validate($validates);

        $file = $request->file('image');

        $name = rand(999999,1);
        $extension = $file->getClientOriginalExtension();
        $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
        Storage::putFileAs('public',$file,$newName);

        $imgDB = 'storage/'.$newName;
        $data->img = $imgDB;
        $data->dsc = $request->dsc;

        $data->save();

        return redirect()->route('admin.carousels.index')->withSuccess('berhasil ditambah');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Carousel::find($id);
        view()->share([
            'data' => $data,
            'notif' => $this->notif()

        ]);

        return view('layouts.carousels.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Carousel::find($id);

        if ($file = $request->file('image') == null){
            $data->img = $request->newImage;
        }else{
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->img = $imgDB;
//            dd($imgDB);
        }


        $data->dsc = $request->dsc;
        $data->save();
        return redirect()->route('admin.carousels.index')->withSuccess('berhasil di update');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Carousel::findOrFail($id);
        $data->delete();

        return redirect()->back()->with('danger','data has been deleted');
    }
}

app/Http/Controllers/Layouts/CategoryController.php
<?php

namespace App\Http\Controllers\Layouts;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            $data = Category::all();

//        dd($data);
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<a href="categories/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.categoriesDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        view()->share([
            'notif' => $this->notif()
        ]);
        return view('layouts.category.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Category();

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);

        $file = $request->file('image');

        $name = rand(999999,1);
        $extension = $file->getClientOriginalExtension();
        $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
        Storage::putFileAs('public',$file,$newName);

        $imgDB = 'storage/'.$newName;
        $data->logo = $imgDB;

        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->dsc;

        $data->save();

        return redirect()->route('admin.categories.index')->with('success','success add UKM');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Category::findOrFail($id);
        view()->share([
            'data' => $data,
                'notif' => $this->notif()
        ]);
        return view('layouts.category.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = Category::findOrFail($id);

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);


        if ($request->file('image')){
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->logo = $imgDB;
        }else{
            $data->logo = $request->newImage;
        }


        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->dsc;

        $data->save();

        return redirect()->route('admin.categories.index')->with('success','edit add UKM');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Category::findOrFail($id);
        $data->delete();

        return redirect()->back()->with('danger','data has been deleted');
    }
}

app/Http/Controllers/Layouts/SuggestionController.php
<?php

namespace App\Http\Controllers\Layouts;

use App\Http\Controllers\Controller;
use App\Models\Carousel;
use App\Models\Suggestions;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Carbon\Carbon;

class SuggestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = Suggestions::all();
            return DataTables::of($data)
                ->addColumn('created_at', function($data){
                    return Carbon::parse($data->created_at)->format('m/d/Y');
                })
                ->rawColumns(['created_at'])
                ->make(true);
        }
        view()->share([
            'notif' => $this->notif()

        ]);
        return view('layouts.suggestions.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use App\Models\User;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public $title;

    public function __construct($title = 'SI-UKM')
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {

        return view('layouts.app');
    }
}

resources/views/layouts/statistika-pendaftaran/filter.blade.php
<x-app-layout >
    @push('style')
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/datatables.min.css">
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
        <style>
            .btn-primary, .btn-primary.disabled {
                box-shadow: 0 0 0 #FFC13B;
                background-color: #FFC13B;
                border-color: #FFC13B;
            }
            .btn-primary:active, .btn-primary:hover, .btn-primary.disabled:active, .btn-primary.disabled:hover {
                background-color: #1E3D59 !important;
            }
            .table-top{
                background-color: #1E3D59 !important;
                color: #FFFFFF;
            }
        </style>
    @endpush
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Statistika</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>
            <x-partials.notice/>

            <div class="section-body">
                <h2 class="section-title">Statistik Pendaftaran</h2>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                            </div>
                            <div class="card-body">
                                <canvas id="myChart4" width="20"></canvas>
                                <div class="dropdown d-inline mr-2">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Pilih Tahun
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{{route('admin.pendaftaran.index')}}">none</a>
                                        @foreach($ukms as $ukm)
                                            <a class="dropdown-item" href="{{route('admin.filter.index',$ukm->id)}}">{{$ukm->name}}</a>
                                        @endforeach
                                    </div>
                                    <br>
                                </div>
                                <br>

                                <div class="table-responsive">
                                    <table class="table table-striped" id="item">
                                        <thead>
                                        <tr class="table-top">
                                            <th style="color: #ffffff">NRP</th>
                                            <th style="color: #ffffff" >Nama Lengkap</th>
                                            <th style="color: #ffffff">Tgl Submit</th>
                                            <th style="color: #ffffff">UKM</th>
                                            <th style="color: #ffffff">Aksi</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @push('script')
        <script src="https://demo.getstisla.com/assets/modules/chart.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function(){
                $('#item').DataTable({
                    @include('components.search'),
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{route('admin.filter.index',$id)}}",
                    },
                    columns: [
                        {
                            data: 'nrp',
                            name: 'nrp'
                        },
                        {
                            data: 'name',
                            name: 'name'
                        },
                        {
                            data: 'created_at',
                            name: 'created_at'
                        },
                        {
                            data: 'ukm_id',
                            name: 'ukm_id'
                        },
                        {
                            data: 'action',
                            name: 'action',
                            orderable: false
                        },
                    ]
                });
            });

            var ctx = document.getElementById("myChart4").getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    datasets: [{
                        data: [
                            @foreach($total as $a)
                            {{$a}}
                            @endforeach
                        ],
                        backgroundColor: [
                            '#191d21',
                            '#63ed7a',
                            '#ffa426',
                            '#fc544b',
                            '#6777ef',
                            '#0e112d',
                            '#9f175e',
                            '#22253e',
                            '#19cd2f',
                            '#0cdd91',
                            '#f1f1f1',
                            '#c7cef1',
                            '#e00c0c',
                            '#000000',
                            '#9aa3dd',
                            '#a2c367',
                            '#124a53',
                            '#6777ef',
                            '#05081d',
                            '#838ce7',
                            '#2e1734',
                            '#2d2e3e',
                            '#e095a3',
                            '#091d51',
                            '#7138e2',

                        ],
                        label: 'Dataset 1'
                    }],
                    labels: [
                        @foreach($nama as $a)
                            '{{$a}}',
                        @endforeach
                    ],
                },
                options: {
                    responsive: true,
                    legend: {
                        position: 'bottom',
                    },
                }
            });
        </script>
    @endpush
</x-app-layout>

resources/views/layouts/statistika-pendaftaran/show.blade.php
<x-app-layout >
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Mahasiswa</h1>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row"> 
                                    <div class="col-2">NRP</div>
                                    <div class="col-10">: {{$data->nrp}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">Nama</div>
                                    <div class="col-10">: {{$data->mahasiswa->name}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">Jurusan</div>
                                    <div class="col-10">: {{$data->mahasiswa->major}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">Alamat</div>
                                    <div class="col-10">: {{$data->mahasiswa->address}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">No Telepon</div>
                                    <div class="col-10">: {{$data->mahasiswa->phone_number}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">UKM yang dituju</div>
                                    <div class="col-10">: {{$data->ukms->name}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">Alasan</div>
                                    <div class="col-10">: {{$data->reason}}</div>
                                </div>
                                <div class="row"> 
                                    <div class="col-2">Tanggal submit</div>
                                    <div class="col-10">: {{date('d-m-Y', strtotime($data->created_at))}}</div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</x-app-layout>